### ISSUE TITLE
Client with "Force Protocol Encryption" support

### ISSUE THREAD

**Issue by Jacc0** [tech-software/TDSProxy#1]
Hi,

Does the proxy support clients with "force Protocol encryption" enabled?
Could not find any documentation on it.
Is there any documentation available?

Kind regards,
Jacco

**Comment by WaldenL** [comment]
Yes. In fact we require encryption to the client side. If client doesn't request it proxy will force it. 

Other than reading the code (and knowing the TDS protocol) there's no external documentation on this, sorry.

**Comment by Jacc0** [comment]
Thanks, for the quick response. I was already suspecting it, but the default certificate store "root" made me confused. One would expect "My" to be the default. I've created a pull request
